; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]

; default_envs = IIC_Scan_2
; default_envs = Keyboard_TCA6424_Test
default_envs = ws2812

src_dir = examples

lib_dir = ./libraries

[env]
platform = espressif32@6.5.0
; PlatformIO espressif32@6.5.0 does not provide a dedicated
; `esp32-s3-devkitc1-n8r2` board ID. Use the official DevKitC-1 target.
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
; debug_tool = esp-builtin
; upload_protocol = esp-builtin

upload_speed = 921600 ; 460800, 512000, 460800, 256000, 115200


build_flags = 
    ; -D BOARD_HAS_PSRAM ;Start external Psram
    -D ARDUINO_USB_CDC_ON_BOOT=1 ;0 is to use an external UART
    ; -UARDUINO_USB_CDC_ON_BOOT

[env:IIC_Scan_2]
build_src_filter = +<IIC_Scan_2/>

[env:Keyboard_TCA6424_Test]
build_src_filter = +<Keyboard_TCA6424_Test/>

[env:ws2812]
build_src_filter = +<ws2812/>
